using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CodeAstrogator.Core;
using Xunit;

namespace CodeAstrogator.Tests
{
    /// <summary>
    /// End-to-end tests for the shadow-repo checkpoints against a real <c>git</c> in a temp workspace.
    /// When git isn't on PATH the tests return early (the feature is disabled in that case anyway).
    /// </summary>
    public class GitCheckpointServiceTests : IDisposable
    {
        private readonly string _root;
        private readonly GitCheckpointService _svc = new GitCheckpointService();
        private static readonly bool HasGit = GitCheckpointService.IsGitAvailable();

        public GitCheckpointServiceTests()
        {
            _root = Path.Combine(Path.GetTempPath(), "cp-test-" + Guid.NewGuid().ToString("n"));
            Directory.CreateDirectory(Path.Combine(_root, "src"));
            Write("src/Program.cs", "one\ntwo\nthree\n");
            Write("README.md", "readme\n");
        }

        public void Dispose()
        {
            try { _svc.DeleteRepo(_root); } catch { }
            try { Directory.Delete(_root, recursive: true); } catch { }
        }

        // ── helpers ─────────────────────────────────────────────────────────

        private string Full(string rel) => Path.Combine(_root, rel.Replace('/', Path.DirectorySeparatorChar));

        private void Write(string rel, string content)
        {
            var path = Full(rel);
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, content);
        }

        private string Read(string rel) => File.ReadAllText(Full(rel));

        private static string Ref(string name) => GitCheckpointService.BuildRefName("session1", name);

        private Task<CheckpointInfo?> SnapshotAsync(string name) =>
            _svc.SnapshotAsync(_root, Ref(name), "test " + name);

        /// <summary>Runs git against the shadow repo directly (used to forge a backdated snapshot).</summary>
        private string Git(string arguments, IDictionary<string, string>? env = null)
        {
            var psi = new ProcessStartInfo
            {
                FileName = "git",
                Arguments = "--git-dir=\"" + Path.Combine(GitCheckpointService.GetRepoDir(_root), ".git") + "\" " + arguments,
                UseShellExecute = false,
                CreateNoWindow = true,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                WorkingDirectory = _root,
            };
            if (env != null)
                foreach (var kv in env)
                    psi.EnvironmentVariables[kv.Key] = kv.Value;
            using (var p = Process.Start(psi)!)
            {
                var stdout = p.StandardOutput.ReadToEnd();
                p.StandardError.ReadToEnd();
                p.WaitForExit();
                return stdout.Trim();
            }
        }

        // ── tests ───────────────────────────────────────────────────────────

        [Fact]
        public async Task Restore_WritesTheOldContentBack()
        {
            if (!HasGit)
                return;
            var before = await SnapshotAsync("1-pre");
            Assert.NotNull(before);

            Write("src/Program.cs", "one\nCHANGED\nthree\nfour\n");
            var result = await _svc.RestoreAsync(_root, before!.Sha, null, Ref("safety-1"));

            Assert.Null(result.Error);
            Assert.Equal("one\ntwo\nthree\n", Read("src/Program.cs"));
            Assert.Equal(1, result.RestoredCount);
        }

        [Fact]
        public async Task Restore_DeletesFilesCreatedAfterTheSnapshot()
        {
            if (!HasGit)
                return;
            var before = await SnapshotAsync("1-pre");
            Write("src/Generated.cs", "// generated by a script\n");

            var result = await _svc.RestoreAsync(_root, before!.Sha, null, Ref("safety-1"));

            Assert.Null(result.Error);
            Assert.False(File.Exists(Full("src/Generated.cs")));
            Assert.Equal(1, result.DeletedCount);
        }

        [Fact]
        public async Task Restore_WithPathFilter_LeavesUnselectedFilesAlone()
        {
            if (!HasGit)
                return;
            var before = await SnapshotAsync("1-pre");
            Write("src/Program.cs", "rewritten\n");
            Write("README.md", "also rewritten\n");

            var result = await _svc.RestoreAsync(_root, before!.Sha,
                new List<string> { "src/Program.cs" }, Ref("safety-1"));

            Assert.Null(result.Error);
            Assert.Equal("one\ntwo\nthree\n", Read("src/Program.cs")); // selected → back to the snapshot
            Assert.Equal("also rewritten\n", Read("README.md"));       // not selected → untouched
        }

        [Fact]
        public async Task Restore_IsUndoable_ViaTheSafetySnapshot()
        {
            if (!HasGit)
                return;
            var before = await SnapshotAsync("1-pre");
            Write("src/Program.cs", "the state we rewind away from\n");

            var result = await _svc.RestoreAsync(_root, before!.Sha, null, Ref("safety-1"));
            Assert.NotNull(result.SafetySha);
            Assert.Equal("one\ntwo\nthree\n", Read("src/Program.cs"));

            // "Redo": restoring the safety snapshot brings the discarded state back.
            var redo = await _svc.RestoreAsync(_root, result.SafetySha!, null, Ref("safety-2"));
            Assert.Null(redo.Error);
            Assert.Equal("the state we rewind away from\n", Read("src/Program.cs"));
        }

        [Fact]
        public async Task Diff_ReportsCountsAndStatuses_ForChangesNoEditToolMade()
        {
            if (!HasGit)
                return;
            // Writing straight to disk stands in for a bash command or a script Claude ran: the
            // pre..post diff has to see it, which is exactly what the edit-tool tracking couldn't.
            var pre = await SnapshotAsync("1-pre");
            Write("src/Program.cs", "one\ntwo\nthree\nfour\nfive\n");
            Write("src/New.cs", "brand new\n");
            File.Delete(Full("README.md"));
            var post = await SnapshotAsync("1-post");

            var changes = await _svc.DiffAsync(_root, pre!.Sha, post!.Sha, null);
            var byPath = changes.ToDictionary(c => c.Path, c => c);

            Assert.Equal(2, byPath["src/Program.cs"].Added);
            Assert.Equal(0, byPath["src/Program.cs"].Removed);
            Assert.Equal("M", byPath["src/Program.cs"].Status);
            Assert.Equal("A", byPath["src/New.cs"].Status);
            Assert.Equal("D", byPath["README.md"].Status);
        }

        [Fact]
        public async Task Diff_AgainstTheWorkTree_NeedsNoSecondSnapshot()
        {
            if (!HasGit)
                return;
            var pre = await SnapshotAsync("1-pre");
            Write("src/Program.cs", "one\ntwo\nthree\nfour\n");

            var changes = await _svc.DiffAsync(_root, pre!.Sha, null, null);

            Assert.Single(changes);
            Assert.Equal("src/Program.cs", changes[0].Path);
            Assert.Equal(1, changes[0].Added);
        }

        [Fact]
        public async Task Snapshot_NeverIncludesTheProjectsOwnGitDirectory()
        {
            if (!HasGit)
                return;
            // A real repo in the workspace: its .git must stay out of every snapshot AND on disk.
            Directory.CreateDirectory(Path.Combine(_root, ".git"));
            Write(".git/HEAD", "ref: refs/heads/main\n");

            var pre = await SnapshotAsync("1-pre");
            Write(".git/HEAD", "ref: refs/heads/other\n");
            var changes = await _svc.DiffAsync(_root, pre!.Sha, null, null);

            Assert.DoesNotContain(changes, c => c.Path.StartsWith(".git", StringComparison.OrdinalIgnoreCase));
            Assert.True(File.Exists(Full(".git/HEAD")));
        }

        [Fact]
        public async Task Snapshot_HonoursGitignore()
        {
            if (!HasGit)
                return;
            Write(".gitignore", "ignored/\n");
            Write("ignored/big.bin", "junk\n");

            var pre = await SnapshotAsync("1-pre");
            Write("ignored/big.bin", "different junk\n");
            var changes = await _svc.DiffAsync(_root, pre!.Sha, null, null);

            Assert.DoesNotContain(changes, c => c.Path.StartsWith("ignored/", StringComparison.Ordinal));
        }

        [Fact]
        public async Task Snapshot_LeavesOversizedFilesOut()
        {
            if (!HasGit)
                return;
            // A checkpoint is for source recovery — a single big binary can otherwise cost more than
            // the whole rest of the workspace (see CheckpointFilter.MaxFileBytes).
            _svc.Filter = new CheckpointFilter { MaxFileBytes = 1024 * 1024 };
            var huge = new byte[_svc.Filter.MaxFileBytes + 4096];
            File.WriteAllBytes(Full("huge.bin"), huge);
            var pre = await SnapshotAsync("1-pre");
            Assert.NotNull(pre);

            Write("src/Program.cs", "one\ntwo\nthree\nfour\n");
            File.WriteAllBytes(Full("huge.bin"), new byte[huge.Length + 4096]);
            var changes = await _svc.DiffAsync(_root, pre!.Sha, null, null);

            Assert.Contains(changes, c => c.Path == "src/Program.cs");
            Assert.DoesNotContain(changes, c => c.Path == "huge.bin");
            var exclude = File.ReadAllText(Path.Combine(
                GitCheckpointService.GetRepoDir(_root), ".git", "info", "exclude"));
            Assert.Contains("huge.bin", exclude);
        }

        [Fact]
        public async Task Snapshot_SkipsBlacklistedExtensions()
        {
            if (!HasGit)
                return;
            _svc.Filter = new CheckpointFilter { Extensions = new[] { ".exe", ".bin" } };
            Write("build/app.exe", "binary-ish\n");
            Write("src/Program.cs", "one\ntwo\nthree\n");

            var pre = await SnapshotAsync("1-pre");
            Write("build/app.exe", "changed\n");
            Write("src/Program.cs", "one\ntwo\nthree\nfour\n");
            var changes = await _svc.DiffAsync(_root, pre!.Sha, null, null);

            Assert.Contains(changes, c => c.Path == "src/Program.cs");
            Assert.DoesNotContain(changes, c => c.Path == "build/app.exe");
        }

        [Fact]
        public async Task Snapshot_WhitelistKeepsOnlyListedExtensions()
        {
            if (!HasGit)
                return;
            _svc.Filter = new CheckpointFilter { Whitelist = true, Extensions = new[] { ".cs" } };
            Write("notes.md", "text\n");
            Write("src/Program.cs", "one\ntwo\nthree\n");

            var pre = await SnapshotAsync("1-pre");
            Write("notes.md", "changed\n");
            Write("src/Program.cs", "one\ntwo\nthree\nfour\n");
            var changes = await _svc.DiffAsync(_root, pre!.Sha, null, null);

            Assert.Contains(changes, c => c.Path == "src/Program.cs");
            Assert.DoesNotContain(changes, c => c.Path == "notes.md");
        }

        [Theory]
        [InlineData(false, "a.exe", 10, true)]   // blacklisted extension
        [InlineData(false, "a.cs", 10, false)]
        [InlineData(true, "a.cs", 10, false)]    // whitelisted
        [InlineData(true, "a.exe", 10, true)]    // not on the whitelist
        [InlineData(false, "big.cs", 5000, true)] // over the size limit
        public void Filter_DecidesPerPathAndSize(bool whitelist, string path, long size, bool expected)
        {
            var filter = new CheckpointFilter
            {
                Whitelist = whitelist,
                Extensions = new[] { whitelist ? ".cs" : ".exe" },
                MaxFileBytes = 1000,
            };
            Assert.Equal(expected, filter.ShouldDrop(path, size));
        }

        [Fact]
        public void Filter_WithoutLimitOrExtensions_KeepsEverything()
        {
            var filter = new CheckpointFilter(); // 0 = no limit, no extensions listed
            Assert.False(filter.ShouldDrop("huge.bin", long.MaxValue));
        }

        [Fact]
        public async Task Prune_DropsOldSnapshotsAndKeepsFreshOnes()
        {
            if (!HasGit)
                return;
            var fresh = await SnapshotAsync("2-pre");
            Assert.NotNull(fresh);

            // Forge a backdated snapshot: same tree, committer date years ago.
            var tree = Git("rev-parse " + fresh!.Sha + "^{tree}");
            var oldSha = Git("commit-tree " + tree + " -m backdated", new Dictionary<string, string>
            {
                ["GIT_COMMITTER_DATE"] = "2001-02-03T04:05:06Z",
                ["GIT_AUTHOR_DATE"] = "2001-02-03T04:05:06Z",
                ["GIT_COMMITTER_NAME"] = "t",
                ["GIT_COMMITTER_EMAIL"] = "t@t",
                ["GIT_AUTHOR_NAME"] = "t",
                ["GIT_AUTHOR_EMAIL"] = "t@t",
            });
            Git("update-ref " + Ref("1-pre") + " " + oldSha);

            var removed = await _svc.PruneAsync(_root, 30);
            Assert.Equal(1, removed);

            var alive = await _svc.FilterExistingAsync(_root, new[] { fresh.Sha, oldSha });
            Assert.Contains(fresh.Sha, alive);
            Assert.DoesNotContain(oldSha, alive); // ref gone + gc'd → the UI shows it as expired
        }

        [Fact]
        public async Task Prune_KeepsEverythingWhenRetentionIsNever()
        {
            if (!HasGit)
                return;
            var snapshot = await SnapshotAsync("1-pre");

            Assert.Equal(0, await _svc.PruneAsync(_root, 0));

            var alive = await _svc.FilterExistingAsync(_root, new[] { snapshot!.Sha });
            Assert.Contains(snapshot.Sha, alive);
        }

        [Fact]
        public async Task List_ReturnsTheSessionsSnapshotsNewestFirst()
        {
            if (!HasGit)
                return;
            var first = await SnapshotAsync("1-pre");
            Write("src/Program.cs", "changed\n");
            var second = await SnapshotAsync("2-pre");

            var list = await _svc.ListAsync(_root, "session1");

            Assert.Contains(list, c => c.Sha == first!.Sha);
            Assert.Contains(list, c => c.Sha == second!.Sha);
        }

        [Theory]
        [InlineData("abc123", "abc123")]
        [InlineData("f7e1a0c2-3b4d-4e5f-8a9b-0c1d2e3f4a5b", "f7e1a0c2-3b4d-4e5f-8a9b-0c1d2e3f4a5b")]
        [InlineData("a b/c:d?e*f", "a-b-c-d-e-f")]
        [InlineData("", "s")]
        [InlineData("...", "s")]
        [InlineData("name.lock", "name-lock")]
        public void SanitizeRefPart_ProducesValidRefComponents(string input, string expected) =>
            Assert.Equal(expected, GitCheckpointService.SanitizeRefPart(input));
    }
}
